spring:
  datasource:
    url:  jdbc:mysql://mydkj123.mysql.rds.aliyuncs.com:3333/myd_wechat_shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username:  mydkjdev
    password:  MYDdev123
  redis:
    #数据库索引
    database: 0
    host: 132.232.85.84
    port: 6333
    password: itjsz
    expire: 300000
    jedis:
      pool:
       #最大连接数
       max-active: 8
       #最大阻塞等待时间(负数表示没限制)
       max-wait: -1
       #最大空闲
       max-idle: 8
       #最小空闲
       min-idle: 0
    #连接超时时间
    timeout: 10000

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: net.itjsz.shirojwt.entity.*
logging:
  level:
    net.itjsz.shirojwt.mapper: debug
  file: sql.log
server:
  port: 8888