spring:
  datasource:
    url:  jdbc:mysql://mydkj123.mysql.rds.aliyuncs.com:3333/myd_wechat_shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username:  *****
    password:  ******

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: net.itjsz.shirojwt.entity.*
logging:
  level:
    net.itjsz.shirojwt.mapper: debug
  file: sql.log
server:
  port: 8888